---
- name: set hostname
  uci: command=set config="system" option="hostname" value={{ hostname }}
  when: hostname != ''
  notify:
    - uci commit system
    - reload system

- name: set timezone
  uci: command=set config="system" option="timezone" value="{{ timezone }}"
  when: timezone != ''
  notify:
    - uci commit system
    - reload system

- name: set zonename
  uci: command=set config="system" option="zonename" value="{{ zonename }}"
  when: zonename != ''
  notify:
    - uci commit system
    - reload system
