---
- name: set hostname
  uci: command=set key="hostname" value="{{ hostname }}"
  with_dict:
    system
  when: {{ hostname }} != ''
  notify:
    - uci commit
    - reload system

- name: set timezone
  uci: command=set key="timezone" value="{{ timezone }}"
  with_dict:
    system
  when: {{ timezone }} != ''
  notify:
    - uci commit
    - reload system

- name: set zonename
  uci: command=set key="zonename" value="{{ zonename }}"
  with_dict:
    system
  when: {{ zonename }} != ''
  notify:
    - uci commit
    - reload system
