---
- name: set system
  uci:
    command: set_object
    config: system
    type: system
    index: 0
    values:
      hostname: '{{hostname}}'
      timezone: '{{timezone}}'
      zonename: '{{ zonename }}'
  notify:
    - uci commit system
    - reload system

- name: set ntp
  uci:
    command: set_object
    config: system
    section: ntp
    values:
      enabled: '{{ enable_ntp_client | int }}'
      enable_server: '{{ enable_ntp_server | int }}'
      server: '{{ntp_servers}}'
  notify:
    - uci commit system
    - reload system

- name: set leds
  uci:
    command: set_object
    config: system
    section: '{{item.key}}'
    values:
      name: "{{item.value.name | default('')}}"
      sysfs: "{{item.value.sysfs | default('')}}"
      default: "{{item.value.default | default('')}}"
      trigger: "{{item.value.trigger | default('')}}"
  with_dict: "{{leds}}"
  when: leds != {}
  notify:
    - uci commit system
    - reload system
