---
- name: set hostname
  uci: command=set config="system" type="system" option="hostname" value={{ hostname }}
  when: hostname != ''
  notify:
    - uci commit system
    - reload system

- name: set timezone
  uci: command=set config="system" type="system" option="timezone" value="{{ timezone }}"
  when: timezone != ''
  notify:
    - uci commit system
    - reload system

- name: set zonename
  uci: command=set config="system" type="system" option="zonename" value="{{ zonename }}"
  when: zonename != ''
  notify:
    - uci commit system
    - reload system

- name: set enable NTP client
  uci: command=set config="system" type="system" section="ntp" option="enabled" value={{ enable_ntp_client | int }}
  when: enable_ntp_client != ''
  notify:
    - uci commit system
    - reload system

- name: set enable NTP server
  uci: command=set config="system" type="system" section="ntp" option="enable_server" value={{ enable_ntp_server | int }}
  when: enable_ntp_server != ''
  notify:
    - uci commit system
    - reload system

- name: set NTP servers
  uci: command=set_list config="system" type="system" section="ntp" option="server" value={{ ntp_servers }}
  when: ntp_servers != ''
  notify:
    - uci commit system
    - reload system

- name: set leds
  include: set_leds.yml
  with_dict: "{{leds}}"
  when: leds != {}
